imports:
  - { resource: "services/form.yml" }
  - { resource: "services/price-rules.yml" }
  - { resource: "services/specific-price-rules.yml" }

parameters:
  coreshop.folder.product: /%coreshop.folder.objects%/products

services:
  # Product Price Rule CONDITIONS
  coreshop.product_price_rule.condition.products:
    class: CoreShop\Bundle\ProductBundle\Rule\Condition\ProductsConditionChecker
    tags:
      - { name: coreshop.product_price_rule.condition, type: products, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Condition\ProductsConfigurationType }

  coreshop.product_price_rule.condition.nested:
    class: CoreShop\Component\Rule\Condition\NestedConditionChecker
    arguments: ['@coreshop.product_price_rule.conditions.processor']
    tags:
      - { name: coreshop.product_price_rule.condition, type: nested, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Condition\ProductPriceNestedConfigurationType }

  coreshop.product_specific_price_rule.condition.nested:
    class: CoreShop\Component\Rule\Condition\NestedConditionChecker
    arguments: ['@coreshop.product_specific_price_rule.conditions.processor']
    tags:
      - { name: coreshop.product_specific_price_rule.condition, type: nested, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Condition\ProductSpecificPriceNestedConfigurationType }

  coreshop.product_price_rule.condition.categories:
    class: CoreShop\Bundle\ProductBundle\Rule\Condition\CategoriesConditionChecker
    tags:
      - { name: coreshop.product_price_rule.condition, type: categories, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Condition\CategoriesConfigurationType }

  coreshop.product_price_rule.condition.timespan:
    class: CoreShop\Bundle\ProductBundle\Rule\Condition\TimeSpanConditionChecker
    tags:
      - { name: coreshop.product_price_rule.condition, type: timespan, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Condition\TimespanConfigurationType }
      - { name: coreshop.product_specific_price_rule.condition, type: timespan, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Condition\TimespanConfigurationType }

  # Product Price Rule ACTIONS
  coreshop.product_price_rule.action.price:
    class: CoreShop\Bundle\ProductBundle\Rule\Action\PriceActionProcessor
    tags:
      - { name: coreshop.product_price_rule.action, type: price, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Action\PriceConfigurationType }
      - { name: coreshop.product_specific_price_rule.action, type: price, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Action\PriceConfigurationType }

  coreshop.product_price_rule.action.discount_amount:
    class: CoreShop\Bundle\ProductBundle\Rule\Action\DiscountAmountActionProcessor
    tags:
      - { name: coreshop.product_price_rule.action, type: discountAmount, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Action\DiscountAmountConfigurationType }
      - { name: coreshop.product_specific_price_rule.action, type: discountAmount, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Action\DiscountAmountConfigurationType }

  coreshop.product_price_rule.action.discount_percent:
    class: CoreShop\Bundle\ProductBundle\Rule\Action\DiscountPercentActionProcessor
    tags:
      - { name: coreshop.product_price_rule.action, type: discountPercent, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Action\DiscountPercentConfigurationType }
      - { name: coreshop.product_specific_price_rule.action, type: discountPercent, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Action\DiscountPercentConfigurationType }

  # Price Calculators
  coreshop.registry.product.price_calculators:
    class: CoreShop\Component\Registry\PrioritizedServiceRegistry
    arguments:
      - CoreShop\Component\Product\Calculator\ProductPriceCalculatorInterface
      - product-price-calculators

  coreshop.product.price_calculator.property_price:
    class: CoreShop\Bundle\ProductBundle\Calculator\PropertyPriceCalculator
    tags:
      - { name: coreshop.product.price_calculator, type: property, priority: 10 }

  coreshop.product.price_calculator.tagged:
    class: CoreShop\Bundle\ProductBundle\Calculator\ProductPriceCalculator
    arguments: ['@coreshop.registry.product.price_calculators']

  coreshop.product.price_calculator.composite:
    class: CoreShop\Bundle\ProductBundle\Calculator\CompositePriceCalculator
    arguments: [['@coreshop.product.price_calculator.tagged']]

  coreshop.product.price_calculator:
    alias: coreshop.product.price_calculator.composite