services:
    _defaults:
        public: true

    CoreShop\Bundle\ProductBundle\Form\Type\ProductSelectionType:
        arguments:
            - '@coreshop.repository.stack.product'
        tags:
            - { name: form.type }
