services:
    _defaults:
        public: true

    coreshop.form.type.product:
        class: CoreShop\Bundle\ProductBundle\Form\Type\ProductSelectionType
        arguments:
            - '@coreshop.repository.stack.product'
        tags:
            - { name: form.type }