services:
    coreshop.registry.product.rules.fetcher:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - 'CoreShop\Component\Product\Rule\Fetcher\ValidRulesFetcherInterface'

    coreshop.product.rules.fetcher:
        class: CoreShop\Component\Product\Rule\Fetcher\CompositeValidRuleFetcher
        arguments:
            - '@coreshop.registry.product.rules.fetcher'


    coreshop.templating.helper.product_valid_rules:
        class: CoreShop\Bundle\ProductBundle\Templating\Helper\ValidPriceRulesHelper
        lazy: true
        arguments:
          - '@coreshop.product.rules.fetcher'
        tags:
            - { name: templating.helper, alias: coreshop_product_price_rules }

    coreshop.twig.extension.product_valid_rules:
        class: CoreShop\Bundle\ProductBundle\Twig\ValidPriceRulesExtension
        public: false
        arguments:
            - '@coreshop.templating.helper.product_valid_rules'
        tags:
            - { name: twig.extension }