services:
    coreshop.registry.product.rules.fetcher:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - 'CoreShop\Component\Product\Rule\Fetcher\ValidRulesFetcherInterface'

    coreshop.product.rules.fetcher:
        class: CoreShop\Component\Product\Rule\Fetcher\CompositeValidRuleFetcher
        arguments:
            - '@coreshop.registry.product.rules.fetcher'


    coreshop.templating.helper.product_valid_rules:
        class: CoreShop\Bundle\ProductBundle\Templating\Helper\ValidPriceRulesHelper
        lazy: true
        arguments:
          - '@coreshop.product.rules.fetcher'
        tags:
            - { name: templating.helper, alias: coreshop_product_price_rules }

    coreshop.twig.extension.product_valid_rules:
        class: CoreShop\Bundle\ProductBundle\Twig\ValidPriceRulesExtension
        public: false
        arguments:
            - '@coreshop.templating.helper.product_valid_rules'
        tags:
            - { name: twig.extension }

    # Rule Assessor
    coreshop.rule.availability_assessor.product_price:
        class: CoreShop\Bundle\RuleBundle\Assessor\RuleAvailabilityAssessor
        arguments:
             - '@coreshop.repository.product_price_rule'
        tags:
            - { name: coreshop.registry.rule_availability_assessor, type: product_price }

    coreshop.rule.availability_assessor.product_specific_price:
        class: CoreShop\Bundle\RuleBundle\Assessor\RuleAvailabilityAssessor
        arguments:
             - '@coreshop.repository.product_specific_price_rule'
        tags:
            - { name: coreshop.registry.rule_availability_assessor, type: product_specific_price }