CoreShop\Component\Product\Model\ProductUnitTranslation:
    type: mappedSuperclass
    table: coreshop_product_unit_translation
    fields:
        id:
            type: integer
            column: id
            id: true
            generator:
              strategy: AUTO
        fullLabel:
            type: string
            column: full_label
        fullPluralLabel:
            type: string
            column: full_plural_label
        shortLabel:
            type: string
            column: short_label
        shortPluralLabel:
            type: string
            column: short_plural_label
        creationDate:
            type: date
            gedmo:
                timestampable:
                    on: create
        modificationDate:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
