CoreShop\Component\Product\Model\ProductUnitDefinition:
    type: mappedSuperclass
    table: coreshop_product_unit_definition
    fields:
        id:
            type: integer
            column: id
            id: true
            generator:
                strategy: AUTO
        product:
            column: product
            type: pimcoreObject
        price:
            column: price
            type: integer
            nullable: true
        precision:
            column: '`precision`'
            type: integer
        conversionRate:
            column: conversion_rate
            type: float
            nullable: true
    manyToOne:
        unit:
            targetEntity: CoreShop\Component\Product\Model\ProductUnitInterface
            joinColumn:
                name: unit
                referencedColumnName: id