pimcore:
    objects:
        class_definitions:
            data:
                map:
                    coreShopProductSpecificPriceRules: CoreShop\Bundle\ProductBundle\CoreExtension\ProductSpecificPriceRules
