CoreShop\Component\Product\Model\ProductSpecificPriceRule:
    properties:
      name:
          - NotBlank: { groups: [coreshop] }
      active:
          - Type: { type: boolean, groups: [coreshop] }